# Generated by Django 6.0.6 on 2026-07-03 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tenant', 'name'],
                'permissions': [('manage_account', 'Can manage account details'), ('create_order_for_account', 'Can create orders for this account')],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('vehicle_type', models.CharField(blank=True, help_text='e.g., Motorcycle, Van, Truck', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manage_drivers', 'Can manage driver assignments'), ('assign_delivery', 'Can be assigned to deliveries'), ('update_delivery_status', 'Can update order delivery status')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Order value in local currency', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.account')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='core.driver')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_all_orders', 'Can view all orders across tenants'), ('assign_order', 'Can assign orders to drivers'), ('cancel_order', 'Can cancel orders')],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(blank=True, help_text='Django Group for tenant-level permission assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant', to='auth.group')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('manage_tenant', 'Can manage tenant settings and users'), ('view_tenant_analytics', 'Can view tenant analytics')],
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='home_tenant',
            field=models.ForeignKey(help_text='Primary tenant this driver belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='home_drivers', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='driver',
            name='shared_tenants',
            field=models.ManyToManyField(blank=True, help_text='Additional tenants this driver can deliver for', related_name='shared_drivers', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='account',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('tenant_admin', 'Tenant Admin'), ('account_manager', 'Account Manager'), ('driver', 'Driver')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('managed_accounts', models.ManyToManyField(blank=True, help_text='Accounts this user manages (for account_manager role)', related_name='managers', to='core.account')),
                ('tenant', models.ForeignKey(blank=True, help_text='Primary tenant for tenant_admins, account_managers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manage_permissions', 'Can manage user permissions and roles')],
            },
        ),
    ]
